---
title: "Reveiw Questions"
output: html_document
---

# 1.  Do the boston-housing.Rmd assignment in github.
Don't forget to show your works, plots included.


# 2. Algorithms and Functions

When speaking of Machine Learning, there are two functions or algorithms involved.
Describe and differentiate the algorithms from the function.

In machine learning the algorithm is the process of vetting a set of functions and evaluating each to find the best fit given the data.  The function is the model chosen for its fit, which ideally takes the best set of predictors to provide a reasonable estimate of the dependent variable. 
 


# .3 RMSE and MAE

Why is RMSE preferrable to MAE?  
When is MAE better? 

RMSE puts increasingly more weight on the outliers the farther the outliers are from the fitted line, while the weight given to outliers in linear with MAE.  As RMSE penalizes models with large outliers more heavily, this scoring is preferable when deviations from the fit estimates are undesirable.  MAE may be too conservative in this case.  On the other hand, MAE is easier to understand as it is a simpler formula.  If distance from the fitted model can be weighted equally, MAE might be the preferable scoring to use do to its simplicity.
